version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: achatdb
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  achat-backend:
    depends_on:
      - mysqldb
    image: achwekharizi1998/devops_project:1.2
    restart: on-failure
    ports:
      - "8089:8089"
    stdin_open: true
    tty: true
volumes:
  db:

