version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  achat-backend:
      depends_on:
        - mysqldb
      image: achwekharizi1998/devops_project:1.2
      restart: on-failure
      environment:
        MYSQL_ROOT_PASSWORD: rootpassword
      ports:
        - "6868:6868"
      stdin_open: true
      tty: true
volumes:
  db:

