version: "3.8"
services:
  db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_DATABASE=achatdb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - springboot-mysql
    ports:
      - "3306:3306"
    volumes:
      - cloudwizard-5arctic3_db_data:/var/lib/mysql

  spring:
    build:
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      - database=db
    depends_on:
      - db
    networks:
      - springboot-mysql
  
volumes:
  cloudwizard-5arctic3_db_data:

networks:
   springboot-mysql:
     driver: bridge
