version: "3.8"
services:
  mysqldb:
    image: mysql:5.5
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3307:3307"
    volumes:
      - db:/var/lib/mysql

  achat-backend:
    depends_on:
      - mysqldb
    build: achwekharizi1998/devops-project:1.2
    restart: on-failure
    ports:
      - "6868:6868"
    stdin_open: true
    tty: true


